# Generated by Django 5.1.1 on 2024-09-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='app_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='author_clas',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='author_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
