# Generated by Django 5.1.1 on 2024-09-17 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_entry_app_name_entry_author_clas_entry_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='author_clas',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='author_name',
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
